### ISSUE TITLE
Merge sort doesn't work on some computers

### ISSUE THREAD

**Issue by Darokrithia** [Darokrithia/PopGenSim#14]
While Merge sort works on every other computer it seg-faults on a single computer.  We need to figure out why this is happening and fix it. 

This possibly entails rewriting the merge sort function.

**Comment by macosten** [comment]
By replacing int_merge_sort with int_qsort, this is effectively solved.

That being said, we now need to (properly) replace all calls to int_merge_sort with int_qsort.
